package com.comtec.ipps.cp.api;

public interface TapiCall {
	/**
	 * ID generated by Tapi.
	 */
	String getId();
	String getExtension();
	String getCallingPartyNumber();
	String getCalledPartyNumber();
	String getTerminalName();
}
